version: "3"

services:
  snorby:
    restart: always
    image: netsiphon/passenger-snorby
    links:
     - mariadb:mysql
    ports:
      - "$SNORBY_PORT:$SNORBY_PORT"
    depends_on:
      - mariadb
    env_file: passenger-snorby.env

  mariadb:
    restart: always
    image: mariadb:latest
    env_file:
     - ./passenger-snorby.env
    ports:
     - "$DB_PORT:$DB_PORT"
    volumes:
     - ./mariadb:/var/lib/mysql
